# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jop/work/NST/NST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jop/work/NST/NST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/jop/work/NST/NST/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jop/work/NST/NST/CMakeFiles /home/jop/work/NST/NST//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jop/work/NST/NST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/jop/work/NST/NST/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NST

# Build rule for target.
NST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NST
.PHONY : NST

# fast build rule for target.
NST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/build
.PHONY : NST/fast

#=============================================================================
# Target rules for targets named NST_autogen_timestamp_deps

# Build rule for target.
NST_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NST_autogen_timestamp_deps
.PHONY : NST_autogen_timestamp_deps

# fast build rule for target.
NST_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST_autogen_timestamp_deps.dir/build.make CMakeFiles/NST_autogen_timestamp_deps.dir/build
.PHONY : NST_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named NST_autogen

# Build rule for target.
NST_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NST_autogen
.PHONY : NST_autogen

# fast build rule for target.
NST_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST_autogen.dir/build.make CMakeFiles/NST_autogen.dir/build
.PHONY : NST_autogen/fast

#=============================================================================
# Target rules for targets named bga_rust

# Build rule for target.
bga_rust: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bga_rust
.PHONY : bga_rust

# fast build rule for target.
bga_rust/fast:
	$(MAKE) $(MAKESILENT) -f BGA/CMakeFiles/bga_rust.dir/build.make BGA/CMakeFiles/bga_rust.dir/build
.PHONY : bga_rust/fast

#=============================================================================
# Target rules for targets named BGACore

# Build rule for target.
BGACore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACore
.PHONY : BGACore

# fast build rule for target.
BGACore/fast:
	$(MAKE) $(MAKESILENT) -f BGA/CMakeFiles/BGACore.dir/build.make BGA/CMakeFiles/BGACore.dir/build
.PHONY : BGACore/fast

#=============================================================================
# Target rules for targets named BGACore_autogen_timestamp_deps

# Build rule for target.
BGACore_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACore_autogen_timestamp_deps
.PHONY : BGACore_autogen_timestamp_deps

# fast build rule for target.
BGACore_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f BGA/CMakeFiles/BGACore_autogen_timestamp_deps.dir/build.make BGA/CMakeFiles/BGACore_autogen_timestamp_deps.dir/build
.PHONY : BGACore_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named BGACore_autogen

# Build rule for target.
BGACore_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACore_autogen
.PHONY : BGACore_autogen

# fast build rule for target.
BGACore_autogen/fast:
	$(MAKE) $(MAKESILENT) -f BGA/CMakeFiles/BGACore_autogen.dir/build.make BGA/CMakeFiles/BGACore_autogen.dir/build
.PHONY : BGACore_autogen/fast

#=============================================================================
# Target rules for targets named BGACoreTests

# Build rule for target.
BGACoreTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACoreTests
.PHONY : BGACoreTests

# fast build rule for target.
BGACoreTests/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/BGACoreTests.dir/build.make BGA/tests/CMakeFiles/BGACoreTests.dir/build
.PHONY : BGACoreTests/fast

#=============================================================================
# Target rules for targets named TestRpgAnalyzer

# Build rule for target.
TestRpgAnalyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRpgAnalyzer
.PHONY : TestRpgAnalyzer

# fast build rule for target.
TestRpgAnalyzer/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/TestRpgAnalyzer.dir/build.make BGA/tests/CMakeFiles/TestRpgAnalyzer.dir/build
.PHONY : TestRpgAnalyzer/fast

#=============================================================================
# Target rules for targets named BGACoreTests_autogen_timestamp_deps

# Build rule for target.
BGACoreTests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACoreTests_autogen_timestamp_deps
.PHONY : BGACoreTests_autogen_timestamp_deps

# fast build rule for target.
BGACoreTests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/BGACoreTests_autogen_timestamp_deps.dir/build.make BGA/tests/CMakeFiles/BGACoreTests_autogen_timestamp_deps.dir/build
.PHONY : BGACoreTests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named BGACoreTests_autogen

# Build rule for target.
BGACoreTests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BGACoreTests_autogen
.PHONY : BGACoreTests_autogen

# fast build rule for target.
BGACoreTests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/BGACoreTests_autogen.dir/build.make BGA/tests/CMakeFiles/BGACoreTests_autogen.dir/build
.PHONY : BGACoreTests_autogen/fast

#=============================================================================
# Target rules for targets named TestRpgAnalyzer_autogen_timestamp_deps

# Build rule for target.
TestRpgAnalyzer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRpgAnalyzer_autogen_timestamp_deps
.PHONY : TestRpgAnalyzer_autogen_timestamp_deps

# fast build rule for target.
TestRpgAnalyzer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/TestRpgAnalyzer_autogen_timestamp_deps.dir/build.make BGA/tests/CMakeFiles/TestRpgAnalyzer_autogen_timestamp_deps.dir/build
.PHONY : TestRpgAnalyzer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named TestRpgAnalyzer_autogen

# Build rule for target.
TestRpgAnalyzer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRpgAnalyzer_autogen
.PHONY : TestRpgAnalyzer_autogen

# fast build rule for target.
TestRpgAnalyzer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f BGA/tests/CMakeFiles/TestRpgAnalyzer_autogen.dir/build.make BGA/tests/CMakeFiles/TestRpgAnalyzer_autogen.dir/build
.PHONY : TestRpgAnalyzer_autogen/fast

#=============================================================================
# Target rules for targets named QtLingo

# Build rule for target.
QtLingo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtLingo
.PHONY : QtLingo

# fast build rule for target.
QtLingo/fast:
	$(MAKE) $(MAKESILENT) -f QtLingo/CMakeFiles/QtLingo.dir/build.make QtLingo/CMakeFiles/QtLingo.dir/build
.PHONY : QtLingo/fast

#=============================================================================
# Target rules for targets named QtLingo_autogen_timestamp_deps

# Build rule for target.
QtLingo_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtLingo_autogen_timestamp_deps
.PHONY : QtLingo_autogen_timestamp_deps

# fast build rule for target.
QtLingo_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f QtLingo/CMakeFiles/QtLingo_autogen_timestamp_deps.dir/build.make QtLingo/CMakeFiles/QtLingo_autogen_timestamp_deps.dir/build
.PHONY : QtLingo_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named QtLingo_autogen

# Build rule for target.
QtLingo_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtLingo_autogen
.PHONY : QtLingo_autogen

# fast build rule for target.
QtLingo_autogen/fast:
	$(MAKE) $(MAKESILENT) -f QtLingo/CMakeFiles/QtLingo_autogen.dir/build.make QtLingo/CMakeFiles/QtLingo_autogen.dir/build
.PHONY : QtLingo_autogen/fast

#=============================================================================
# Target rules for targets named MockDataPlugin

# Build rule for target.
MockDataPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockDataPlugin
.PHONY : MockDataPlugin

# fast build rule for target.
MockDataPlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin.dir/build.make src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin.dir/build
.PHONY : MockDataPlugin/fast

#=============================================================================
# Target rules for targets named MockDataPlugin_autogen_timestamp_deps

# Build rule for target.
MockDataPlugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockDataPlugin_autogen_timestamp_deps
.PHONY : MockDataPlugin_autogen_timestamp_deps

# fast build rule for target.
MockDataPlugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin_autogen_timestamp_deps.dir/build.make src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin_autogen_timestamp_deps.dir/build
.PHONY : MockDataPlugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MockDataPlugin_autogen

# Build rule for target.
MockDataPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockDataPlugin_autogen
.PHONY : MockDataPlugin_autogen

# fast build rule for target.
MockDataPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin_autogen.dir/build.make src/plugins/MockDataPlugin/CMakeFiles/MockDataPlugin_autogen.dir/build
.PHONY : MockDataPlugin_autogen/fast

#=============================================================================
# Target rules for targets named UnrpycPlugin

# Build rule for target.
UnrpycPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnrpycPlugin
.PHONY : UnrpycPlugin

# fast build rule for target.
UnrpycPlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin.dir/build.make src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin.dir/build
.PHONY : UnrpycPlugin/fast

#=============================================================================
# Target rules for targets named UnrpycPlugin_autogen_timestamp_deps

# Build rule for target.
UnrpycPlugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnrpycPlugin_autogen_timestamp_deps
.PHONY : UnrpycPlugin_autogen_timestamp_deps

# fast build rule for target.
UnrpycPlugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin_autogen_timestamp_deps.dir/build.make src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin_autogen_timestamp_deps.dir/build
.PHONY : UnrpycPlugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named UnrpycPlugin_autogen

# Build rule for target.
UnrpycPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnrpycPlugin_autogen
.PHONY : UnrpycPlugin_autogen

# fast build rule for target.
UnrpycPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin_autogen.dir/build.make src/plugins/UnrpycPlugin/CMakeFiles/UnrpycPlugin_autogen.dir/build
.PHONY : UnrpycPlugin_autogen/fast

#=============================================================================
# Target rules for targets named MockTranslationPlugin

# Build rule for target.
MockTranslationPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockTranslationPlugin
.PHONY : MockTranslationPlugin

# fast build rule for target.
MockTranslationPlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin.dir/build.make src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin.dir/build
.PHONY : MockTranslationPlugin/fast

#=============================================================================
# Target rules for targets named MockTranslationPlugin_autogen_timestamp_deps

# Build rule for target.
MockTranslationPlugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockTranslationPlugin_autogen_timestamp_deps
.PHONY : MockTranslationPlugin_autogen_timestamp_deps

# fast build rule for target.
MockTranslationPlugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin_autogen_timestamp_deps.dir/build.make src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin_autogen_timestamp_deps.dir/build
.PHONY : MockTranslationPlugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MockTranslationPlugin_autogen

# Build rule for target.
MockTranslationPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MockTranslationPlugin_autogen
.PHONY : MockTranslationPlugin_autogen

# fast build rule for target.
MockTranslationPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin_autogen.dir/build.make src/plugins/MockTranslationPlugin/CMakeFiles/MockTranslationPlugin_autogen.dir/build
.PHONY : MockTranslationPlugin_autogen/fast

#=============================================================================
# Target rules for targets named LuaTranslationPlugin

# Build rule for target.
LuaTranslationPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuaTranslationPlugin
.PHONY : LuaTranslationPlugin

# fast build rule for target.
LuaTranslationPlugin/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin.dir/build.make src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin.dir/build
.PHONY : LuaTranslationPlugin/fast

#=============================================================================
# Target rules for targets named LuaTranslationPlugin_autogen_timestamp_deps

# Build rule for target.
LuaTranslationPlugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuaTranslationPlugin_autogen_timestamp_deps
.PHONY : LuaTranslationPlugin_autogen_timestamp_deps

# fast build rule for target.
LuaTranslationPlugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin_autogen_timestamp_deps.dir/build.make src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin_autogen_timestamp_deps.dir/build
.PHONY : LuaTranslationPlugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named LuaTranslationPlugin_autogen

# Build rule for target.
LuaTranslationPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LuaTranslationPlugin_autogen
.PHONY : LuaTranslationPlugin_autogen

# fast build rule for target.
LuaTranslationPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin_autogen.dir/build.make src/plugins/LuaTranslationPlugin/CMakeFiles/LuaTranslationPlugin_autogen.dir/build
.PHONY : LuaTranslationPlugin_autogen/fast

#=============================================================================
# Target rules for targets named Injection

# Build rule for target.
Injection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Injection
.PHONY : Injection

# fast build rule for target.
Injection/fast:
	$(MAKE) $(MAKESILENT) -f Injection/CMakeFiles/Injection.dir/build.make Injection/CMakeFiles/Injection.dir/build
.PHONY : Injection/fast

#=============================================================================
# Target rules for targets named Injection_autogen_timestamp_deps

# Build rule for target.
Injection_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Injection_autogen_timestamp_deps
.PHONY : Injection_autogen_timestamp_deps

# fast build rule for target.
Injection_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Injection/CMakeFiles/Injection_autogen_timestamp_deps.dir/build.make Injection/CMakeFiles/Injection_autogen_timestamp_deps.dir/build
.PHONY : Injection_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Injection_autogen

# Build rule for target.
Injection_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Injection_autogen
.PHONY : Injection_autogen

# fast build rule for target.
Injection_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Injection/CMakeFiles/Injection_autogen.dir/build.make Injection/CMakeFiles/Injection_autogen.dir/build
.PHONY : Injection_autogen/fast

NST_autogen/UVLADIE3JM/qrc_resources.o: NST_autogen/UVLADIE3JM/qrc_resources.cpp.o
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.o

# target to build an object file
NST_autogen/UVLADIE3JM/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/UVLADIE3JM/qrc_resources.cpp.o
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.cpp.o

NST_autogen/UVLADIE3JM/qrc_resources.i: NST_autogen/UVLADIE3JM/qrc_resources.cpp.i
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.i

# target to preprocess a source file
NST_autogen/UVLADIE3JM/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/UVLADIE3JM/qrc_resources.cpp.i
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.cpp.i

NST_autogen/UVLADIE3JM/qrc_resources.s: NST_autogen/UVLADIE3JM/qrc_resources.cpp.s
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.s

# target to generate assembly for a file
NST_autogen/UVLADIE3JM/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/UVLADIE3JM/qrc_resources.cpp.s
.PHONY : NST_autogen/UVLADIE3JM/qrc_resources.cpp.s

NST_autogen/mocs_compilation.o: NST_autogen/mocs_compilation.cpp.o
.PHONY : NST_autogen/mocs_compilation.o

# target to build an object file
NST_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/mocs_compilation.cpp.o
.PHONY : NST_autogen/mocs_compilation.cpp.o

NST_autogen/mocs_compilation.i: NST_autogen/mocs_compilation.cpp.i
.PHONY : NST_autogen/mocs_compilation.i

# target to preprocess a source file
NST_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/mocs_compilation.cpp.i
.PHONY : NST_autogen/mocs_compilation.cpp.i

NST_autogen/mocs_compilation.s: NST_autogen/mocs_compilation.cpp.s
.PHONY : NST_autogen/mocs_compilation.s

# target to generate assembly for a file
NST_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/NST_autogen/mocs_compilation.cpp.s
.PHONY : NST_autogen/mocs_compilation.cpp.s

src/controllers/searchcontroller.o: src/controllers/searchcontroller.cpp.o
.PHONY : src/controllers/searchcontroller.o

# target to build an object file
src/controllers/searchcontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/searchcontroller.cpp.o
.PHONY : src/controllers/searchcontroller.cpp.o

src/controllers/searchcontroller.i: src/controllers/searchcontroller.cpp.i
.PHONY : src/controllers/searchcontroller.i

# target to preprocess a source file
src/controllers/searchcontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/searchcontroller.cpp.i
.PHONY : src/controllers/searchcontroller.cpp.i

src/controllers/searchcontroller.s: src/controllers/searchcontroller.cpp.s
.PHONY : src/controllers/searchcontroller.s

# target to generate assembly for a file
src/controllers/searchcontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/searchcontroller.cpp.s
.PHONY : src/controllers/searchcontroller.cpp.s

src/controllers/shortcutcontroller.o: src/controllers/shortcutcontroller.cpp.o
.PHONY : src/controllers/shortcutcontroller.o

# target to build an object file
src/controllers/shortcutcontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/shortcutcontroller.cpp.o
.PHONY : src/controllers/shortcutcontroller.cpp.o

src/controllers/shortcutcontroller.i: src/controllers/shortcutcontroller.cpp.i
.PHONY : src/controllers/shortcutcontroller.i

# target to preprocess a source file
src/controllers/shortcutcontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/shortcutcontroller.cpp.i
.PHONY : src/controllers/shortcutcontroller.cpp.i

src/controllers/shortcutcontroller.s: src/controllers/shortcutcontroller.cpp.s
.PHONY : src/controllers/shortcutcontroller.s

# target to generate assembly for a file
src/controllers/shortcutcontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/shortcutcontroller.cpp.s
.PHONY : src/controllers/shortcutcontroller.cpp.s

src/controllers/updatecontroller.o: src/controllers/updatecontroller.cpp.o
.PHONY : src/controllers/updatecontroller.o

# target to build an object file
src/controllers/updatecontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/updatecontroller.cpp.o
.PHONY : src/controllers/updatecontroller.cpp.o

src/controllers/updatecontroller.i: src/controllers/updatecontroller.cpp.i
.PHONY : src/controllers/updatecontroller.i

# target to preprocess a source file
src/controllers/updatecontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/updatecontroller.cpp.i
.PHONY : src/controllers/updatecontroller.cpp.i

src/controllers/updatecontroller.s: src/controllers/updatecontroller.cpp.s
.PHONY : src/controllers/updatecontroller.s

# target to generate assembly for a file
src/controllers/updatecontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/controllers/updatecontroller.cpp.s
.PHONY : src/controllers/updatecontroller.cpp.s

src/core/main.o: src/core/main.cpp.o
.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i
.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s
.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

src/core/rpgrelationanalyzer.o: src/core/rpgrelationanalyzer.cpp.o
.PHONY : src/core/rpgrelationanalyzer.o

# target to build an object file
src/core/rpgrelationanalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/rpgrelationanalyzer.cpp.o
.PHONY : src/core/rpgrelationanalyzer.cpp.o

src/core/rpgrelationanalyzer.i: src/core/rpgrelationanalyzer.cpp.i
.PHONY : src/core/rpgrelationanalyzer.i

# target to preprocess a source file
src/core/rpgrelationanalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/rpgrelationanalyzer.cpp.i
.PHONY : src/core/rpgrelationanalyzer.cpp.i

src/core/rpgrelationanalyzer.s: src/core/rpgrelationanalyzer.cpp.s
.PHONY : src/core/rpgrelationanalyzer.s

# target to generate assembly for a file
src/core/rpgrelationanalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/rpgrelationanalyzer.cpp.s
.PHONY : src/core/rpgrelationanalyzer.cpp.s

src/core/translationserver.o: src/core/translationserver.cpp.o
.PHONY : src/core/translationserver.o

# target to build an object file
src/core/translationserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/translationserver.cpp.o
.PHONY : src/core/translationserver.cpp.o

src/core/translationserver.i: src/core/translationserver.cpp.i
.PHONY : src/core/translationserver.i

# target to preprocess a source file
src/core/translationserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/translationserver.cpp.i
.PHONY : src/core/translationserver.cpp.i

src/core/translationserver.s: src/core/translationserver.cpp.s
.PHONY : src/core/translationserver.s

# target to generate assembly for a file
src/core/translationserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/core/translationserver.cpp.s
.PHONY : src/core/translationserver.cpp.s

src/dialogs/customprogressdialog.o: src/dialogs/customprogressdialog.cpp.o
.PHONY : src/dialogs/customprogressdialog.o

# target to build an object file
src/dialogs/customprogressdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/customprogressdialog.cpp.o
.PHONY : src/dialogs/customprogressdialog.cpp.o

src/dialogs/customprogressdialog.i: src/dialogs/customprogressdialog.cpp.i
.PHONY : src/dialogs/customprogressdialog.i

# target to preprocess a source file
src/dialogs/customprogressdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/customprogressdialog.cpp.i
.PHONY : src/dialogs/customprogressdialog.cpp.i

src/dialogs/customprogressdialog.s: src/dialogs/customprogressdialog.cpp.s
.PHONY : src/dialogs/customprogressdialog.s

# target to generate assembly for a file
src/dialogs/customprogressdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/customprogressdialog.cpp.s
.PHONY : src/dialogs/customprogressdialog.cpp.s

src/dialogs/fontmanagerdialog.o: src/dialogs/fontmanagerdialog.cpp.o
.PHONY : src/dialogs/fontmanagerdialog.o

# target to build an object file
src/dialogs/fontmanagerdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/fontmanagerdialog.cpp.o
.PHONY : src/dialogs/fontmanagerdialog.cpp.o

src/dialogs/fontmanagerdialog.i: src/dialogs/fontmanagerdialog.cpp.i
.PHONY : src/dialogs/fontmanagerdialog.i

# target to preprocess a source file
src/dialogs/fontmanagerdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/fontmanagerdialog.cpp.i
.PHONY : src/dialogs/fontmanagerdialog.cpp.i

src/dialogs/fontmanagerdialog.s: src/dialogs/fontmanagerdialog.cpp.s
.PHONY : src/dialogs/fontmanagerdialog.s

# target to generate assembly for a file
src/dialogs/fontmanagerdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/fontmanagerdialog.cpp.s
.PHONY : src/dialogs/fontmanagerdialog.cpp.s

src/dialogs/loadprojectdialog.o: src/dialogs/loadprojectdialog.cpp.o
.PHONY : src/dialogs/loadprojectdialog.o

# target to build an object file
src/dialogs/loadprojectdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/loadprojectdialog.cpp.o
.PHONY : src/dialogs/loadprojectdialog.cpp.o

src/dialogs/loadprojectdialog.i: src/dialogs/loadprojectdialog.cpp.i
.PHONY : src/dialogs/loadprojectdialog.i

# target to preprocess a source file
src/dialogs/loadprojectdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/loadprojectdialog.cpp.i
.PHONY : src/dialogs/loadprojectdialog.cpp.i

src/dialogs/loadprojectdialog.s: src/dialogs/loadprojectdialog.cpp.s
.PHONY : src/dialogs/loadprojectdialog.s

# target to generate assembly for a file
src/dialogs/loadprojectdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/loadprojectdialog.cpp.s
.PHONY : src/dialogs/loadprojectdialog.cpp.s

src/dialogs/plugindebuggerdialog.o: src/dialogs/plugindebuggerdialog.cpp.o
.PHONY : src/dialogs/plugindebuggerdialog.o

# target to build an object file
src/dialogs/plugindebuggerdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/plugindebuggerdialog.cpp.o
.PHONY : src/dialogs/plugindebuggerdialog.cpp.o

src/dialogs/plugindebuggerdialog.i: src/dialogs/plugindebuggerdialog.cpp.i
.PHONY : src/dialogs/plugindebuggerdialog.i

# target to preprocess a source file
src/dialogs/plugindebuggerdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/plugindebuggerdialog.cpp.i
.PHONY : src/dialogs/plugindebuggerdialog.cpp.i

src/dialogs/plugindebuggerdialog.s: src/dialogs/plugindebuggerdialog.cpp.s
.PHONY : src/dialogs/plugindebuggerdialog.s

# target to generate assembly for a file
src/dialogs/plugindebuggerdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/plugindebuggerdialog.cpp.s
.PHONY : src/dialogs/plugindebuggerdialog.cpp.s

src/dialogs/pluginmanagerdialog.o: src/dialogs/pluginmanagerdialog.cpp.o
.PHONY : src/dialogs/pluginmanagerdialog.o

# target to build an object file
src/dialogs/pluginmanagerdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/pluginmanagerdialog.cpp.o
.PHONY : src/dialogs/pluginmanagerdialog.cpp.o

src/dialogs/pluginmanagerdialog.i: src/dialogs/pluginmanagerdialog.cpp.i
.PHONY : src/dialogs/pluginmanagerdialog.i

# target to preprocess a source file
src/dialogs/pluginmanagerdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/pluginmanagerdialog.cpp.i
.PHONY : src/dialogs/pluginmanagerdialog.cpp.i

src/dialogs/pluginmanagerdialog.s: src/dialogs/pluginmanagerdialog.cpp.s
.PHONY : src/dialogs/pluginmanagerdialog.s

# target to generate assembly for a file
src/dialogs/pluginmanagerdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/pluginmanagerdialog.cpp.s
.PHONY : src/dialogs/pluginmanagerdialog.cpp.s

src/dialogs/processselectordialog.o: src/dialogs/processselectordialog.cpp.o
.PHONY : src/dialogs/processselectordialog.o

# target to build an object file
src/dialogs/processselectordialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/processselectordialog.cpp.o
.PHONY : src/dialogs/processselectordialog.cpp.o

src/dialogs/processselectordialog.i: src/dialogs/processselectordialog.cpp.i
.PHONY : src/dialogs/processselectordialog.i

# target to preprocess a source file
src/dialogs/processselectordialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/processselectordialog.cpp.i
.PHONY : src/dialogs/processselectordialog.cpp.i

src/dialogs/processselectordialog.s: src/dialogs/processselectordialog.cpp.s
.PHONY : src/dialogs/processselectordialog.s

# target to generate assembly for a file
src/dialogs/processselectordialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/processselectordialog.cpp.s
.PHONY : src/dialogs/processselectordialog.cpp.s

src/dialogs/scripteditordialog.o: src/dialogs/scripteditordialog.cpp.o
.PHONY : src/dialogs/scripteditordialog.o

# target to build an object file
src/dialogs/scripteditordialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/scripteditordialog.cpp.o
.PHONY : src/dialogs/scripteditordialog.cpp.o

src/dialogs/scripteditordialog.i: src/dialogs/scripteditordialog.cpp.i
.PHONY : src/dialogs/scripteditordialog.i

# target to preprocess a source file
src/dialogs/scripteditordialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/scripteditordialog.cpp.i
.PHONY : src/dialogs/scripteditordialog.cpp.i

src/dialogs/scripteditordialog.s: src/dialogs/scripteditordialog.cpp.s
.PHONY : src/dialogs/scripteditordialog.s

# target to generate assembly for a file
src/dialogs/scripteditordialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/scripteditordialog.cpp.s
.PHONY : src/dialogs/scripteditordialog.cpp.s

src/dialogs/searchdialog.o: src/dialogs/searchdialog.cpp.o
.PHONY : src/dialogs/searchdialog.o

# target to build an object file
src/dialogs/searchdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/searchdialog.cpp.o
.PHONY : src/dialogs/searchdialog.cpp.o

src/dialogs/searchdialog.i: src/dialogs/searchdialog.cpp.i
.PHONY : src/dialogs/searchdialog.i

# target to preprocess a source file
src/dialogs/searchdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/searchdialog.cpp.i
.PHONY : src/dialogs/searchdialog.cpp.i

src/dialogs/searchdialog.s: src/dialogs/searchdialog.cpp.s
.PHONY : src/dialogs/searchdialog.s

# target to generate assembly for a file
src/dialogs/searchdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/searchdialog.cpp.s
.PHONY : src/dialogs/searchdialog.cpp.s

src/dialogs/settingsdialog.o: src/dialogs/settingsdialog.cpp.o
.PHONY : src/dialogs/settingsdialog.o

# target to build an object file
src/dialogs/settingsdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/settingsdialog.cpp.o
.PHONY : src/dialogs/settingsdialog.cpp.o

src/dialogs/settingsdialog.i: src/dialogs/settingsdialog.cpp.i
.PHONY : src/dialogs/settingsdialog.i

# target to preprocess a source file
src/dialogs/settingsdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/settingsdialog.cpp.i
.PHONY : src/dialogs/settingsdialog.cpp.i

src/dialogs/settingsdialog.s: src/dialogs/settingsdialog.cpp.s
.PHONY : src/dialogs/settingsdialog.s

# target to generate assembly for a file
src/dialogs/settingsdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/dialogs/settingsdialog.cpp.s
.PHONY : src/dialogs/settingsdialog.cpp.s

src/managers/bgadatamanager.o: src/managers/bgadatamanager.cpp.o
.PHONY : src/managers/bgadatamanager.o

# target to build an object file
src/managers/bgadatamanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/bgadatamanager.cpp.o
.PHONY : src/managers/bgadatamanager.cpp.o

src/managers/bgadatamanager.i: src/managers/bgadatamanager.cpp.i
.PHONY : src/managers/bgadatamanager.i

# target to preprocess a source file
src/managers/bgadatamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/bgadatamanager.cpp.i
.PHONY : src/managers/bgadatamanager.cpp.i

src/managers/bgadatamanager.s: src/managers/bgadatamanager.cpp.s
.PHONY : src/managers/bgadatamanager.s

# target to generate assembly for a file
src/managers/bgadatamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/bgadatamanager.cpp.s
.PHONY : src/managers/bgadatamanager.cpp.s

src/managers/projectdatamanager.o: src/managers/projectdatamanager.cpp.o
.PHONY : src/managers/projectdatamanager.o

# target to build an object file
src/managers/projectdatamanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/projectdatamanager.cpp.o
.PHONY : src/managers/projectdatamanager.cpp.o

src/managers/projectdatamanager.i: src/managers/projectdatamanager.cpp.i
.PHONY : src/managers/projectdatamanager.i

# target to preprocess a source file
src/managers/projectdatamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/projectdatamanager.cpp.i
.PHONY : src/managers/projectdatamanager.cpp.i

src/managers/projectdatamanager.s: src/managers/projectdatamanager.cpp.s
.PHONY : src/managers/projectdatamanager.s

# target to generate assembly for a file
src/managers/projectdatamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/projectdatamanager.cpp.s
.PHONY : src/managers/projectdatamanager.cpp.s

src/managers/smartfiltermanager.o: src/managers/smartfiltermanager.cpp.o
.PHONY : src/managers/smartfiltermanager.o

# target to build an object file
src/managers/smartfiltermanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/smartfiltermanager.cpp.o
.PHONY : src/managers/smartfiltermanager.cpp.o

src/managers/smartfiltermanager.i: src/managers/smartfiltermanager.cpp.i
.PHONY : src/managers/smartfiltermanager.i

# target to preprocess a source file
src/managers/smartfiltermanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/smartfiltermanager.cpp.i
.PHONY : src/managers/smartfiltermanager.cpp.i

src/managers/smartfiltermanager.s: src/managers/smartfiltermanager.cpp.s
.PHONY : src/managers/smartfiltermanager.s

# target to generate assembly for a file
src/managers/smartfiltermanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/smartfiltermanager.cpp.s
.PHONY : src/managers/smartfiltermanager.cpp.s

src/managers/translationservicemanager.o: src/managers/translationservicemanager.cpp.o
.PHONY : src/managers/translationservicemanager.o

# target to build an object file
src/managers/translationservicemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/translationservicemanager.cpp.o
.PHONY : src/managers/translationservicemanager.cpp.o

src/managers/translationservicemanager.i: src/managers/translationservicemanager.cpp.i
.PHONY : src/managers/translationservicemanager.i

# target to preprocess a source file
src/managers/translationservicemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/translationservicemanager.cpp.i
.PHONY : src/managers/translationservicemanager.cpp.i

src/managers/translationservicemanager.s: src/managers/translationservicemanager.cpp.s
.PHONY : src/managers/translationservicemanager.s

# target to generate assembly for a file
src/managers/translationservicemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/managers/translationservicemanager.cpp.s
.PHONY : src/managers/translationservicemanager.cpp.s

src/plugins/LuaPlugin.o: src/plugins/LuaPlugin.cpp.o
.PHONY : src/plugins/LuaPlugin.o

# target to build an object file
src/plugins/LuaPlugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaPlugin.cpp.o
.PHONY : src/plugins/LuaPlugin.cpp.o

src/plugins/LuaPlugin.i: src/plugins/LuaPlugin.cpp.i
.PHONY : src/plugins/LuaPlugin.i

# target to preprocess a source file
src/plugins/LuaPlugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaPlugin.cpp.i
.PHONY : src/plugins/LuaPlugin.cpp.i

src/plugins/LuaPlugin.s: src/plugins/LuaPlugin.cpp.s
.PHONY : src/plugins/LuaPlugin.s

# target to generate assembly for a file
src/plugins/LuaPlugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaPlugin.cpp.s
.PHONY : src/plugins/LuaPlugin.cpp.s

src/plugins/LuaScriptManager.o: src/plugins/LuaScriptManager.cpp.o
.PHONY : src/plugins/LuaScriptManager.o

# target to build an object file
src/plugins/LuaScriptManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaScriptManager.cpp.o
.PHONY : src/plugins/LuaScriptManager.cpp.o

src/plugins/LuaScriptManager.i: src/plugins/LuaScriptManager.cpp.i
.PHONY : src/plugins/LuaScriptManager.i

# target to preprocess a source file
src/plugins/LuaScriptManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaScriptManager.cpp.i
.PHONY : src/plugins/LuaScriptManager.cpp.i

src/plugins/LuaScriptManager.s: src/plugins/LuaScriptManager.cpp.s
.PHONY : src/plugins/LuaScriptManager.s

# target to generate assembly for a file
src/plugins/LuaScriptManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaScriptManager.cpp.s
.PHONY : src/plugins/LuaScriptManager.cpp.s

src/plugins/LuaTranslationPlugin/luatranslationservice.o: src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.o
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.o

# target to build an object file
src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.o
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.o

src/plugins/LuaTranslationPlugin/luatranslationservice.i: src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.i
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.i

# target to preprocess a source file
src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.i
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.i

src/plugins/LuaTranslationPlugin/luatranslationservice.s: src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.s
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.s

# target to generate assembly for a file
src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.s
.PHONY : src/plugins/LuaTranslationPlugin/luatranslationservice.cpp.s

src/plugins/PluginManager.o: src/plugins/PluginManager.cpp.o
.PHONY : src/plugins/PluginManager.o

# target to build an object file
src/plugins/PluginManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/PluginManager.cpp.o
.PHONY : src/plugins/PluginManager.cpp.o

src/plugins/PluginManager.i: src/plugins/PluginManager.cpp.i
.PHONY : src/plugins/PluginManager.i

# target to preprocess a source file
src/plugins/PluginManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/PluginManager.cpp.i
.PHONY : src/plugins/PluginManager.cpp.i

src/plugins/PluginManager.s: src/plugins/PluginManager.cpp.s
.PHONY : src/plugins/PluginManager.s

# target to generate assembly for a file
src/plugins/PluginManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/plugins/PluginManager.cpp.s
.PHONY : src/plugins/PluginManager.cpp.s

src/ui/customtitlebar.o: src/ui/customtitlebar.cpp.o
.PHONY : src/ui/customtitlebar.o

# target to build an object file
src/ui/customtitlebar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/customtitlebar.cpp.o
.PHONY : src/ui/customtitlebar.cpp.o

src/ui/customtitlebar.i: src/ui/customtitlebar.cpp.i
.PHONY : src/ui/customtitlebar.i

# target to preprocess a source file
src/ui/customtitlebar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/customtitlebar.cpp.i
.PHONY : src/ui/customtitlebar.cpp.i

src/ui/customtitlebar.s: src/ui/customtitlebar.cpp.s
.PHONY : src/ui/customtitlebar.s

# target to generate assembly for a file
src/ui/customtitlebar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/customtitlebar.cpp.s
.PHONY : src/ui/customtitlebar.cpp.s

src/ui/filetranslationwidget.o: src/ui/filetranslationwidget.cpp.o
.PHONY : src/ui/filetranslationwidget.o

# target to build an object file
src/ui/filetranslationwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/filetranslationwidget.cpp.o
.PHONY : src/ui/filetranslationwidget.cpp.o

src/ui/filetranslationwidget.i: src/ui/filetranslationwidget.cpp.i
.PHONY : src/ui/filetranslationwidget.i

# target to preprocess a source file
src/ui/filetranslationwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/filetranslationwidget.cpp.i
.PHONY : src/ui/filetranslationwidget.cpp.i

src/ui/filetranslationwidget.s: src/ui/filetranslationwidget.cpp.s
.PHONY : src/ui/filetranslationwidget.s

# target to generate assembly for a file
src/ui/filetranslationwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/filetranslationwidget.cpp.s
.PHONY : src/ui/filetranslationwidget.cpp.s

src/ui/mainwindow.o: src/ui/mainwindow.cpp.o
.PHONY : src/ui/mainwindow.o

# target to build an object file
src/ui/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/mainwindow.cpp.o
.PHONY : src/ui/mainwindow.cpp.o

src/ui/mainwindow.i: src/ui/mainwindow.cpp.i
.PHONY : src/ui/mainwindow.i

# target to preprocess a source file
src/ui/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/mainwindow.cpp.i
.PHONY : src/ui/mainwindow.cpp.i

src/ui/mainwindow.s: src/ui/mainwindow.cpp.s
.PHONY : src/ui/mainwindow.s

# target to generate assembly for a file
src/ui/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/mainwindow.cpp.s
.PHONY : src/ui/mainwindow.cpp.s

src/ui/menubar.o: src/ui/menubar.cpp.o
.PHONY : src/ui/menubar.o

# target to build an object file
src/ui/menubar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/menubar.cpp.o
.PHONY : src/ui/menubar.cpp.o

src/ui/menubar.i: src/ui/menubar.cpp.i
.PHONY : src/ui/menubar.i

# target to preprocess a source file
src/ui/menubar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/menubar.cpp.i
.PHONY : src/ui/menubar.cpp.i

src/ui/menubar.s: src/ui/menubar.cpp.s
.PHONY : src/ui/menubar.s

# target to generate assembly for a file
src/ui/menubar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/menubar.cpp.s
.PHONY : src/ui/menubar.cpp.s

src/ui/realtimetranslationwidget.o: src/ui/realtimetranslationwidget.cpp.o
.PHONY : src/ui/realtimetranslationwidget.o

# target to build an object file
src/ui/realtimetranslationwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/realtimetranslationwidget.cpp.o
.PHONY : src/ui/realtimetranslationwidget.cpp.o

src/ui/realtimetranslationwidget.i: src/ui/realtimetranslationwidget.cpp.i
.PHONY : src/ui/realtimetranslationwidget.i

# target to preprocess a source file
src/ui/realtimetranslationwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/realtimetranslationwidget.cpp.i
.PHONY : src/ui/realtimetranslationwidget.cpp.i

src/ui/realtimetranslationwidget.s: src/ui/realtimetranslationwidget.cpp.s
.PHONY : src/ui/realtimetranslationwidget.s

# target to generate assembly for a file
src/ui/realtimetranslationwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/realtimetranslationwidget.cpp.s
.PHONY : src/ui/realtimetranslationwidget.cpp.s

src/ui/relationitem.o: src/ui/relationitem.cpp.o
.PHONY : src/ui/relationitem.o

# target to build an object file
src/ui/relationitem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationitem.cpp.o
.PHONY : src/ui/relationitem.cpp.o

src/ui/relationitem.i: src/ui/relationitem.cpp.i
.PHONY : src/ui/relationitem.i

# target to preprocess a source file
src/ui/relationitem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationitem.cpp.i
.PHONY : src/ui/relationitem.cpp.i

src/ui/relationitem.s: src/ui/relationitem.cpp.s
.PHONY : src/ui/relationitem.s

# target to generate assembly for a file
src/ui/relationitem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationitem.cpp.s
.PHONY : src/ui/relationitem.cpp.s

src/ui/relationshipwidget.o: src/ui/relationshipwidget.cpp.o
.PHONY : src/ui/relationshipwidget.o

# target to build an object file
src/ui/relationshipwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationshipwidget.cpp.o
.PHONY : src/ui/relationshipwidget.cpp.o

src/ui/relationshipwidget.i: src/ui/relationshipwidget.cpp.i
.PHONY : src/ui/relationshipwidget.i

# target to preprocess a source file
src/ui/relationshipwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationshipwidget.cpp.i
.PHONY : src/ui/relationshipwidget.cpp.i

src/ui/relationshipwidget.s: src/ui/relationshipwidget.cpp.s
.PHONY : src/ui/relationshipwidget.s

# target to generate assembly for a file
src/ui/relationshipwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/relationshipwidget.cpp.s
.PHONY : src/ui/relationshipwidget.cpp.s

src/ui/translationcontextmenu.o: src/ui/translationcontextmenu.cpp.o
.PHONY : src/ui/translationcontextmenu.o

# target to build an object file
src/ui/translationcontextmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/translationcontextmenu.cpp.o
.PHONY : src/ui/translationcontextmenu.cpp.o

src/ui/translationcontextmenu.i: src/ui/translationcontextmenu.cpp.i
.PHONY : src/ui/translationcontextmenu.i

# target to preprocess a source file
src/ui/translationcontextmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/translationcontextmenu.cpp.i
.PHONY : src/ui/translationcontextmenu.cpp.i

src/ui/translationcontextmenu.s: src/ui/translationcontextmenu.cpp.s
.PHONY : src/ui/translationcontextmenu.s

# target to generate assembly for a file
src/ui/translationcontextmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NST.dir/build.make CMakeFiles/NST.dir/src/ui/translationcontextmenu.cpp.s
.PHONY : src/ui/translationcontextmenu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... BGACoreTests_autogen"
	@echo "... BGACoreTests_autogen_timestamp_deps"
	@echo "... BGACore_autogen"
	@echo "... BGACore_autogen_timestamp_deps"
	@echo "... Injection_autogen"
	@echo "... Injection_autogen_timestamp_deps"
	@echo "... LuaTranslationPlugin_autogen"
	@echo "... LuaTranslationPlugin_autogen_timestamp_deps"
	@echo "... MockDataPlugin_autogen"
	@echo "... MockDataPlugin_autogen_timestamp_deps"
	@echo "... MockTranslationPlugin_autogen"
	@echo "... MockTranslationPlugin_autogen_timestamp_deps"
	@echo "... NST_autogen"
	@echo "... NST_autogen_timestamp_deps"
	@echo "... QtLingo_autogen"
	@echo "... QtLingo_autogen_timestamp_deps"
	@echo "... TestRpgAnalyzer_autogen"
	@echo "... TestRpgAnalyzer_autogen_timestamp_deps"
	@echo "... UnrpycPlugin_autogen"
	@echo "... UnrpycPlugin_autogen_timestamp_deps"
	@echo "... bga_rust"
	@echo "... BGACore"
	@echo "... BGACoreTests"
	@echo "... Injection"
	@echo "... LuaTranslationPlugin"
	@echo "... MockDataPlugin"
	@echo "... MockTranslationPlugin"
	@echo "... NST"
	@echo "... QtLingo"
	@echo "... TestRpgAnalyzer"
	@echo "... UnrpycPlugin"
	@echo "... NST_autogen/UVLADIE3JM/qrc_resources.o"
	@echo "... NST_autogen/UVLADIE3JM/qrc_resources.i"
	@echo "... NST_autogen/UVLADIE3JM/qrc_resources.s"
	@echo "... NST_autogen/mocs_compilation.o"
	@echo "... NST_autogen/mocs_compilation.i"
	@echo "... NST_autogen/mocs_compilation.s"
	@echo "... src/controllers/searchcontroller.o"
	@echo "... src/controllers/searchcontroller.i"
	@echo "... src/controllers/searchcontroller.s"
	@echo "... src/controllers/shortcutcontroller.o"
	@echo "... src/controllers/shortcutcontroller.i"
	@echo "... src/controllers/shortcutcontroller.s"
	@echo "... src/controllers/updatecontroller.o"
	@echo "... src/controllers/updatecontroller.i"
	@echo "... src/controllers/updatecontroller.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/core/rpgrelationanalyzer.o"
	@echo "... src/core/rpgrelationanalyzer.i"
	@echo "... src/core/rpgrelationanalyzer.s"
	@echo "... src/core/translationserver.o"
	@echo "... src/core/translationserver.i"
	@echo "... src/core/translationserver.s"
	@echo "... src/dialogs/customprogressdialog.o"
	@echo "... src/dialogs/customprogressdialog.i"
	@echo "... src/dialogs/customprogressdialog.s"
	@echo "... src/dialogs/fontmanagerdialog.o"
	@echo "... src/dialogs/fontmanagerdialog.i"
	@echo "... src/dialogs/fontmanagerdialog.s"
	@echo "... src/dialogs/loadprojectdialog.o"
	@echo "... src/dialogs/loadprojectdialog.i"
	@echo "... src/dialogs/loadprojectdialog.s"
	@echo "... src/dialogs/plugindebuggerdialog.o"
	@echo "... src/dialogs/plugindebuggerdialog.i"
	@echo "... src/dialogs/plugindebuggerdialog.s"
	@echo "... src/dialogs/pluginmanagerdialog.o"
	@echo "... src/dialogs/pluginmanagerdialog.i"
	@echo "... src/dialogs/pluginmanagerdialog.s"
	@echo "... src/dialogs/processselectordialog.o"
	@echo "... src/dialogs/processselectordialog.i"
	@echo "... src/dialogs/processselectordialog.s"
	@echo "... src/dialogs/scripteditordialog.o"
	@echo "... src/dialogs/scripteditordialog.i"
	@echo "... src/dialogs/scripteditordialog.s"
	@echo "... src/dialogs/searchdialog.o"
	@echo "... src/dialogs/searchdialog.i"
	@echo "... src/dialogs/searchdialog.s"
	@echo "... src/dialogs/settingsdialog.o"
	@echo "... src/dialogs/settingsdialog.i"
	@echo "... src/dialogs/settingsdialog.s"
	@echo "... src/managers/bgadatamanager.o"
	@echo "... src/managers/bgadatamanager.i"
	@echo "... src/managers/bgadatamanager.s"
	@echo "... src/managers/projectdatamanager.o"
	@echo "... src/managers/projectdatamanager.i"
	@echo "... src/managers/projectdatamanager.s"
	@echo "... src/managers/smartfiltermanager.o"
	@echo "... src/managers/smartfiltermanager.i"
	@echo "... src/managers/smartfiltermanager.s"
	@echo "... src/managers/translationservicemanager.o"
	@echo "... src/managers/translationservicemanager.i"
	@echo "... src/managers/translationservicemanager.s"
	@echo "... src/plugins/LuaPlugin.o"
	@echo "... src/plugins/LuaPlugin.i"
	@echo "... src/plugins/LuaPlugin.s"
	@echo "... src/plugins/LuaScriptManager.o"
	@echo "... src/plugins/LuaScriptManager.i"
	@echo "... src/plugins/LuaScriptManager.s"
	@echo "... src/plugins/LuaTranslationPlugin/luatranslationservice.o"
	@echo "... src/plugins/LuaTranslationPlugin/luatranslationservice.i"
	@echo "... src/plugins/LuaTranslationPlugin/luatranslationservice.s"
	@echo "... src/plugins/PluginManager.o"
	@echo "... src/plugins/PluginManager.i"
	@echo "... src/plugins/PluginManager.s"
	@echo "... src/ui/customtitlebar.o"
	@echo "... src/ui/customtitlebar.i"
	@echo "... src/ui/customtitlebar.s"
	@echo "... src/ui/filetranslationwidget.o"
	@echo "... src/ui/filetranslationwidget.i"
	@echo "... src/ui/filetranslationwidget.s"
	@echo "... src/ui/mainwindow.o"
	@echo "... src/ui/mainwindow.i"
	@echo "... src/ui/mainwindow.s"
	@echo "... src/ui/menubar.o"
	@echo "... src/ui/menubar.i"
	@echo "... src/ui/menubar.s"
	@echo "... src/ui/realtimetranslationwidget.o"
	@echo "... src/ui/realtimetranslationwidget.i"
	@echo "... src/ui/realtimetranslationwidget.s"
	@echo "... src/ui/relationitem.o"
	@echo "... src/ui/relationitem.i"
	@echo "... src/ui/relationitem.s"
	@echo "... src/ui/relationshipwidget.o"
	@echo "... src/ui/relationshipwidget.i"
	@echo "... src/ui/relationshipwidget.s"
	@echo "... src/ui/translationcontextmenu.o"
	@echo "... src/ui/translationcontextmenu.i"
	@echo "... src/ui/translationcontextmenu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/jop/work/NST/NST/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

