// This file is autogenerated. Changes will be overwritten.
#include "JF5ZEU5S3Q/moc_translationservice.cpp"
#include "UVLADIE3JM/moc_google_translate_service.cpp"
#include "UVLADIE3JM/moc_llm_translation_service.cpp"
